//! Core kernel modules for the wattetheria Rust MVP.

pub mod brain;
pub mod civilization;
pub mod game;
pub mod governance;
pub mod map;
pub mod security;
pub mod storage;
pub mod tasks;
pub mod types;

pub use brain::mcp;
pub use brain::night_shift;
pub use brain::plugin_registry;
pub use brain::policy_engine;
pub use civilization::emergency;
pub use civilization::galaxy;
pub use civilization::identities;
pub use civilization::metrics;
pub use civilization::missions;
pub use civilization::organizations;
pub use civilization::profiles;
pub use civilization::topics;
pub use game::catalog as game_catalog;
pub use game::progression as game_progression;
pub use governance::mailbox;
pub use governance::oracle;
pub use map::consequence as map_consequence;
pub use map::registry as map_registry;
pub use map::state as map_state;
pub use map::travel as map_travel;
pub use map::validator as map_validator;
pub use security::admission;
pub use security::capabilities;
pub use security::hashcash;
pub use security::identity;
pub use security::signing;
pub use security::trust;
pub use storage::audit;
pub use storage::data_ops;
pub use storage::event_log;
pub use storage::online_proof;
pub use storage::summary;
pub use tasks::galaxy_task;
pub use tasks::swarm_bridge;
pub use tasks::task_engine;
